### ISSUE TITLE
get and search appointment APIs

### ISSUE THREAD

**Issue by jbride** [redhat-naps-da/vaccination-scheduling#2]
A few GET APIs to retrieve  an appointment would be nice.  ie:
-   `Appointment getByAppointmentId( Long appointmentId )`
-  `List<Appointment> getByPersonId ( Long personId )`

Also the ability to search for appointments by vaccination_center and person name.

**Comment by dvanbalen** [comment]
Implemented the two endpoints above, as well as getByVaccinationCenter ( String vaccinationCenter )
